name: TestSiteApplify
favicon: null
layout_spectrum: 0.2494
typography_spectrum: 0.14015
title: Testing this out
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#f17934'
    - '#212b5f'
    - '#757c9b'
    - '#adb1c3'
  brandStrength: 1
  lightness: 0.44432587758637965
  saturation: 0.27943774755112827
  rhythmicContrast: 0.8597948173992336
purpose: []
