name: TestSiteApplify
favicon: null
layout_spectrum: 0.7309080013073981
typography_spectrum: 0.8372352216392756
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.05478296964429319
  lightness: 0.44432587758637965
  saturation: 0.27943774755112827
  rhythmicContrast: 0.8597948173992336
purpose: []
