name: TestSiteApplify
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34543
title: Testing this out
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f27934'
    - '#212c5f'
    - '#000000'
    - '#ff0000'
    - '#800000'
  brandStrength: 1
  lightness: 0.44432587758637965
  saturation: 0.27943774755112827
  rhythmicContrast: 0.8597948173992336
purpose: []
